### ISSUE TITLE
[Feature Request] Hotkey to position client on screen?

### ISSUE THREAD

**Issue by MystarB** [YvesW/client-resizer#1]
Love the plugin first off. The way I use it is just using hotkey resizing to switch between when I'm either doing an afk skill and playing another game and want the window smaller/on my second monitor,  to make it smaller if I'm training a skill like herblore where the smaller game window helps, or to even make it smaller and make my alt's client bigger when I'm focusing on it doing quests and the like.

However, before I used the plugin I would always go into the runelite settings, set my client size, and then tick/untick "always contain in screen". Doing so would let me either drag it to another monitor, or to just align it perfectly in the corner of my screen as not doing so can lead to issues such as "Remember client position" not functioning correctly if the client is even a pixel off screen.

My request is to have an option that 1) upon request gets the x/y positioning of your client and 2) have the ability to hotkey moving it into said x/y positions.

Sidenote, when talking to a friend about this, he mentioned a thing he does that's similar is utilizing the "always on top" feature aswell. Just thought I'd put that here aswell.

**Comment by YvesW** [comment]
So if I understand correctly, you'd like to set the client's X & Y using a hotkey? I'll try to take a look at it this weekend. Maybe I can use some code from the core-client and repurpose it, but generally speaking moving or maximizing windows using Java is kind of awful, so no promises.

**Comment by YvesW** [comment]
Screwed around with it a bit, but it doesn't seem to work. However, that's probably also due to my lack of understanding of the client's clientUI & frame. I might check it out again at some point when I have time.
For now I recommend creating an AHK script, which would be way easier.

**Comment by YvesW** [comment]
Took me a while to figure out (thanks Hooder for the tip!), but it I added the option to reposition the client to a specific X and Y in https://github.com/YvesW/client-resizer/commit/2ef0d46b9a62e003909aa64728bf65766521604f

I'll push a slightly changed commit to master soon + submit it to the phub soon-ish. Merging will depend on the time of the reviewers, so that'll be soon(tm).
