### ISSUE TITLE
Add option to disable chat messages

### ISSUE THREAD

**Issue by darrenswhite** [YvesW/client-resizer#4]
Could a checkbox be added to enable/disable chat box messages such as `Your RuneLite game size / client size was changed by the Client Resizer plugin. Check your config if you'd like to change this.`

**Comment by YvesW** [comment]
I originally added the message to prevent people from installing the plugin, setting it up, forgetting about the plugin, and then complaining about their client "randomly" being resized in the RuneLite Discord.
I can see how the message can get spammy though, so for now I've added an option to disable it under an ``Advanced`` config section (https://github.com/YvesW/client-resizer/commit/a83c3252d5e0e5ed17e60b2d0c5da7b188ad68fe). It might take a bit for the PR to get merged though; the pluginhub queue is quite backed up.
