### ISSUE TITLE
Disable hotkey options while the bank pin widget is open

### ISSUE THREAD

**Issue by Felanbird** [YvesW/client-resizer#5]
My thought process for setting up client-resizer is what key(s) would I press the least, and my assumption was the keys on the numpad which I never press.... except to type in my bank pin.

I do still think it would be preferred to keep the hotkey(s) on the numpad, and due to how little time you spend inputting your bank pin, preventing the hotkeys from running when the window is open seems like the best plan.

**Comment by YvesW** [comment]
Oh, never thought about this situation since I always use key combos like ``ctrl+L``. I'll try to take a look at it when I have time.

**Comment by YvesW** [comment]
Added in https://github.com/YvesW/client-resizer/commit/5a3a905fceec88dcae3e62cbb922fceb515d1aed: by default, the plugin will now ignore purely numerical hotkeys while the bank pin container is open.

I'll probably try to add #6, wait a week or so before submitting to the hub so it can sit/cook a bit, then spot an error/think of something new 1 hour after it's been merged into the hub.
