### ISSUE TITLE
Add option to automatically change resizable scaling without resizing the client

### ISSUE THREAD

**Issue by pirssi** [YvesW/client-resizer#8]
I'd be very much interested in being able to automatize only the resizable scaling percentage in the Stretched mode plugin. 
I wasn't to able to figure out a way to change it without also resizing the client (with either automatic or hotkey resizing). 

I personally use an AHK script to resize and move my RuneLite window, since resizing the whole window instead of just the client/game allows it to stay the same "dimensions" whether the RuneLite sidebar is open or not when 'Resize type' is set to 'Keep window size' in RuneLite settings. 
To try to put it simpler, the Client Resizer plugin essentially ignores the RuneLite sidebar since it can only resize the actual game client, which causes different window size if resizing with the sidebar closed, versus resizing with the sidebar open and then closing it. 
E.g. `resize to 1000x600 with sidebar closed = 1000x600 client size`, vs. `resize to 1000x600 with sidebar open, close the sidebar = 1250x600 client size.`

Unless the plugin could determine whether a) the sidebar is open or closed and b) the 'Resize type' is set to 'Keep window size' or 'Keep game size' and resize the client taking this into account to keep the window size the same (which sounds like a huge hassle just to accommodate cases like this though it would be amazing to see this implented as well), I would love to see an option to only adjust the scaling per monitor. :)

**Comment by YvesW** [comment]
I could probably add an advanced option ``Do not resize client`` or something like that which is disabled by default and just returns at the beginning of ``setGameSize``. Would that suffice? You will never be able to resize the client with the setting enabled though.

**Comment by pirssi** [comment]
Sure, as long as the plugin would automatically adjust resizable scaling per monitor, that sounds awesome! I assume other features (snap back/anti-drag) would still also work?

**Comment by YvesW** [comment]
Yeah, it'd just not changes the size config setting but do everything else. Snap back/anti-drag don't resize the client (they change position), so they should still work.

I'll get to it when I have time.

**Comment by YvesW** [comment]
Added in e0f4bed0306391fc7c277c0715c98340bed06f93 as an advanced config option.

It will appear on the hub when it's reviewed. Probably between now and a couple weeks.
